# Not used on production. For testing that this works ahead of deployment.
version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file: ./app/.env
    volumes:
      - ./app:/var/www/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bedrock_development
      MYSQL_USER: bedrock_user
      MYSQL_PASSWORD: passbedrock_passwordword
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 3400:8080
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
